[package]
name = "evol"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15" }
serde = { version = "1.0", features = ["derive"] }
ron = "0.8.0"
petgraph = { version = "0.6.5", features = ["serde-1"] }